### ISSUE TITLE
Error VGeosearch is not defined

### ISSUE THREAD

**Issue by rafalilloblanco** [fega/vue2-leaflet-geosearch#11]
Spanish: Hola, tengo el siguiente error, he seguido todos los pasos de la documentación, pero me aparece el siguiente error y no consigo hacer funcionar el módulo.

English: Hello, I have the following error, I have followed all the steps in the documentation, but the following error appears and I cannot get the module to work.

PD: I speak Spanish, in case it is easier to understand

![Captura](https://user-images.githubusercontent.com/17000368/71184131-8ff7f280-2279-11ea-8d22-ee94c4141bf3.JPG)

**Comment by fega** [comment]
Como estas importando el módulo?

**Comment by rafalilloblanco** [comment]
Perdona, ya está funcionando a la perfección. Muchas gracias por su ayuda.
