### ISSUE TITLE
Remove/Destroy Function Fails

### ISSUE THREAD

**Issue by jpgilchrist** [fega/vue2-leaflet-geosearch#4]
Hey, first and foremost, nice little plugin wrapper. However, I'm seeing a pretty low hanging issue.

`this.markerCluster` is never defined anywhere, so `this.$parent.removeLayer(this.markerCluster)` always fails. Thus, i'm getting an error on every destroy of the map, which isn't good. 

Secondly, your npm repo is out of date as I see you have `this.$parent.removeLayer(this.markerCluster)` in your git source code, but in the npm module it's `this.parent.removeLayer(this.markerCluster)` which also causes it's own error in remove/destroy due to it not being defined either.

**Comment by fega** [comment]
@jpgilchrist Could you send a PR?

**Comment by jpgilchrist** [comment]
@fega the PR is already merged?

**Comment by fega** [comment]
this one? https://github.com/fega/vue2-leaflet-geosearch/pull/5

yes, sorry I forgot to close the issue, and probably to release a new version. 

Thanks!

**Comment by fega** [comment]
Just to confirm, I did the release 2 months ago.
