### ISSUE TITLE
New installation error

### ISSUE THREAD

**Issue by ascweb** [fega/vue2-leaflet-geosearch#8]
Hello,

I'm new in Vue.js and I'm getting error importing your module:

`  import { OpenStreetMapProvider } from 'leaflet-geosearch';
    import { VGeosearch } from 'vue2-leaflet-geosearch';`

**The error**:

>   `Errors compiling template:`
>
>  `text "module.exports = "\n" outside root element will be ignored.`
>
> `1  |  module.exports = "\n<div>\n\n</div>\n";`
   
But if I change  your template removing the prop **lang="html"** it's imported perfectly.

**Comment by fega** [comment]
Nice, I saw that you forked the project, send me a PR
